config/routes.rb
Kayapinterest::Application.routes.draw do
  root :to =>"gambars#index"
  resources :gambars
  get "gambars/index"
  get "gambars/new"
  get "gambars/edit"

end

app/models/gambar.rb
class Gambar < ActiveRecord::Base
	#attr_accessible :title, :lokasi
	validates :title, presence: true
	validates :lokasi, presence: true
	mount_uploader :lokasi, GambarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gambars_controller.rb
class GambarsController < ApplicationController
  def index
  	@gambar = Gambar.all
  end

  def new
  	@gambar=Gambar.new
  end

  def edit
    @gambar = Gambar.find_by_id(params[:id])
  end

  def create
  	@gambar=Gambar.new(params_gambar)
  	if @gambar.save
      flash[:notice] = "Success add image"
  	 redirect_to action: 'index'
    else 
      flash[:error] = "Lengkapi Data"
      render 'new'
    end
end

def update
  @gambar=Gambar.find_by_id(params[:id])
  if @gambar.update(params_gambar)
    flash[:notice]="success update"
    redirect_to action: 'index';
  else
    flash[:error] = "Lengkapi Data"
      render 'edit'
    end
  end

  def destroy
    @gambar=Gambar.find_by_id(params[:id])
    if @gambar.destroy
      @gambar.remove_lokasi
      flash[:notice]="success delete"
      redirect_to action: 'index';
    else
       flash[:error] = "fails delete a records"
    redirect_to action: 'index'
  end
end


private
def params_gambar
	params.require(:gambar).permit(:title, :lokasi)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gambars/edit.html.erb
<%= form_for @gambar do|f| %>
<%= f.label :title %>
</br>
<%= f.text_field :title %>
 </br>
<%= f.file_field :lokasi %>

</br>
<%= f.submit :submit %>
<% end %>

app/views/gambars/index.html.erb
<%= link_to "Show mah Fancybox!", "#hello", class: "fancybox" %>

<div style="display:none;">
  <div id="hello">
  Hello world!
  </div>
</div>



<div class="row">
<% @gambar.each do |gambar| %>
<div class="col-sm-6 col-md-3">
    <div class="thumbnail">
     <%= link_to gambar.lokasi_url.to_s , :class=>'fancybox'  do %>

    <%= image_tag gambar.lokasi_url(:thumb).to_s, :class=>'img-rounded'  %>
    
    <%end%>

    <div class="caption" align="center">
            <h3 ><%=gambar.title%></h3>
            <span><%= link_to 'edit', edit_gambar_path(gambar.id) %></span>
            <span>|</span>
            <span><%= link_to 'delete', gambar_path(gambar.id), method: "DELETE", data: {confirm: 'Delete this data?'} %></span>
        
        
      
    </div>
    </div>
    </div>



<%end%>


 <!--

  <% @gambar.each do |gambar| %>
  <%end%>

app/views/gambars/new.html.erb
<%= form_for @gambar, :html=> {:multipart => true} do|f| %>
<%= f.label :title %>
</br>
<%= f.text_field :title %>
<%= @gambar.errors[:title].first unless @gambar.errors[:gambar].blank? %>
 </br>
<%= f.file_field :lokasi %>
<%= @gambar.errors[:lokasi].first unless @gambar.errors[:gambar].blank? %>

</br>
<%= f.submit :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kayapinterest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>





<div class="navbar navbar-fixedtop
navbar-inverse" role="navigation">
<div class="container">
<div class="navbar-header">
<button type="button" class="navbar-toggle"
data-toggle="collapse"
datatarget=".navbar-collapse">


</button>
<%= link_to 'Kaya Pinterest', root_path, :class=>"navbar-brand" %> 

</div>
<div class="collapse navbar-collapse">
<ul class="nav navbar-nav navbar-right">
<li><%= link_to 'Home',  root_path %></li>
<li><%= link_to 'Upload', new_gambar_path %><li>
</ul>
</div>
</div>
</div>
<!-- flash -->
<% flash.each do |key, value| %>
 <h3><font color="red"><%= content_tag :div, value, class: "flash #{key}" %> </h3></font>
<% end %>

<%= yield %>

</body>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->

</html>